name: Keep Streamlit Warm

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:          # allow manual run from the Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Ping app (homepage)
        run: |
          set -e
          curl -A "keepalive-bot/1.0" -sSfl --max-time 15 "$APP_URL" >/dev/null
      - name: Ping app (health)
        run: |
          # Health path helps wake the backend without rendering the full UI
          curl -A "keepalive-bot/1.0" -sSfl --max-time 15 "$APP_URL/_stcore/health" >/dev/null
    env:
      APP_URL: ${{ secrets.STREAMLIT_APP_URL }}