[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501
runOnSave = false
folderWatchBlacklist = ["*/torch/**"]

[commands]
postinstall = "pip install huggingface-hub==0.10.1"

[watcher]
watcherType = "none"